### PR TITLE
major refactor of code

### PR DESCRIPTION
**Pull request by Darkflame72**
Rewrite code

### CODE REVIEW

**Comment by Darkflame72** [comment]
Need to add models so responses are not just dictionaries

**Comment by Darkflame72** [comment]
This should be ready although I should add data classes for it

**Comment by Darkflame72** [comment]
@AjayACST is there any progress on this?

**Comment by Darkflame72** [comment]
Is this ready?

**Comment by Darkflame72** [comment]
Before merge we need to bump version number to v1.0.0

**Review by AjayACST — APPROVED** [review]

**Pull request merged**
